// Generated by Apple Swift version 4.0 effective-3.2 (swiftlang-900.0.65 clang-900.0.37)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("clovergoclient")

SWIFT_PROTOCOL("_TtP14clovergoclient20AddOrderNoteDelegate_")
@protocol AddOrderNoteDelegate
- (void)addOrderNote:(NSString * _Nonnull)note;
@end

@class CardApplicationIdentifier;

SWIFT_PROTOCOL("_TtP14clovergoclient12AidSelection_")
@protocol AidSelection
- (void)selectApplicationIdentifierWithCardApplicationIdentifier:(CardApplicationIdentifier * _Nullable)cardApplicationIdentifier;
@end

typedef SWIFT_ENUM(NSInteger, CLVGoTransactionType) {
  CLVGoTransactionTypeUnknown = 0,
  CLVGoTransactionTypeKeyed = 1,
  CLVGoTransactionTypeAuth = 2,
  CLVGoTransactionTypeManualrefund = 3,
  CLVGoTransactionTypePreauth = 4,
  CLVGoTransactionTypePurchase = 5,
};


SWIFT_CLASS("_TtC14clovergoclient25CardApplicationIdentifier")
@interface CardApplicationIdentifier : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationLabel;
@property (nonatomic, readonly, copy) NSString * _Nonnull applicationIdentifier;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class ReaderInfo;
enum CardReaderErrorEvent : NSInteger;
enum CardReaderEvent : NSInteger;

SWIFT_PROTOCOL("_TtP14clovergoclient18CardReaderDelegate_")
@protocol CardReaderDelegate
- (void)onConnectedWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo;
- (void)onDisconnectedWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo;
- (void)onErrorWithEvent:(enum CardReaderErrorEvent)event;
- (void)onReadyWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo;
- (void)onReaderResetProgressWithEvent:(enum CardReaderEvent)event;
- (void)onCardReaderDiscoveredWithReaders:(NSArray<ReaderInfo *> * _Nonnull)readers;
@optional
- (void)onPlugged;
@end

typedef SWIFT_ENUM(NSInteger, CardReaderErrorEvent) {
  CardReaderErrorEventInitialization_failed = 0,
  CardReaderErrorEventReader_error = 1,
  CardReaderErrorEventReader_data_not_avaliable = 2,
  CardReaderErrorEventCard_error = 3,
  CardReaderErrorEventCard_not_supported = 4,
  CardReaderErrorEventCard_reader_transaction_aborted = 5,
  CardReaderErrorEventPairing_error = 6,
};

typedef SWIFT_ENUM(NSInteger, CardReaderEvent) {
  CardReaderEventCard_swiped = 0,
  CardReaderEventCard_tapped = 1,
  CardReaderEventSwipe_failed = 2,
  CardReaderEventEmv_card_swiped_error = 3,
  CardReaderEventEmv_dip_failed_3_attempts = 4,
  CardReaderEventEmv_card_dip_failed = 5,
  CardReaderEventEmv_card_inserted = 6,
  CardReaderEventClear_aid_pk_complete = 7,
  CardReaderEventAid_flush_complete = 8,
  CardReaderEventPublic_key_flush_complete = 9,
  CardReaderEventDol_flush_complete = 10,
  CardReaderEventInitialization_complete = 11,
  CardReaderEventCalibration_in_progress = 12,
  CardReaderEventEmv_card_removed = 13,
  CardReaderEventPairing_complete = 14,
  CardReaderEventContactless_failed_try_again = 15,
  CardReaderEventSwipe_dip_tap_card = 16,
  CardReaderEventRemove_card = 17,
};

typedef SWIFT_ENUM(NSInteger, CardType) {
  CardTypeVISA = 0,
  CardTypeMASTERCARD = 1,
  CardTypeDISCOVER = 2,
  CardTypeAMEX = 3,
  CardTypeDINNERS = 4,
  CardTypeJCB = 5,
  CardTypeUNIONPAY = 6,
  CardTypeDEFAULT = 7,
};


SWIFT_CLASS("_TtC14clovergoclient11CardUtility")
@interface CardUtility : NSObject
+ (BOOL)validateCardNumberWithCardNumber:(NSString * _Nonnull)cardNumber SWIFT_WARN_UNUSED_RESULT;
+ (enum CardType)getCardTypeWithCardNumber:(NSString * _Nonnull)cardNumber SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum OfflineMode : NSInteger;
enum Env : NSInteger;
@class Inventory;
@class CloverGoError;
@class TaxRate;
@class KeyedRequest;
@protocol TransactionDelegate;
@class Order;
@class Merchant;

SWIFT_CLASS("_TtC14clovergoclient8CloverGo")
@interface CloverGo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) CloverGo * _Nonnull sharedInstance;)
+ (CloverGo * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(CloverGo * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL allowAutoConnect;)
+ (BOOL)allowAutoConnect SWIFT_WARN_UNUSED_RESULT;
+ (void)setAllowAutoConnect:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL overrideDuplicateTransaction;)
+ (BOOL)overrideDuplicateTransaction SWIFT_WARN_UNUSED_RESULT;
+ (void)setOverrideDuplicateTransaction:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL overrideAddressVerification;)
+ (BOOL)overrideAddressVerification SWIFT_WARN_UNUSED_RESULT;
+ (void)setOverrideAddressVerification:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum OfflineMode offlineMode;)
+ (enum OfflineMode)offlineMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setOfflineMode:(enum OfflineMode)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)initializeWithAccessToken:(NSString * _Nonnull)accessToken apiKey:(NSString * _Nonnull)apiKey secret:(NSString * _Nonnull)secret env:(enum Env)env;
- (void)loadInventoryWithForceReload:(BOOL)forceReload success:(void (^ _Nonnull)(NSArray<Inventory *> * _Nonnull))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)loadTaxesWithForceReload:(BOOL)forceReload success:(void (^ _Nonnull)(NSArray<TaxRate *> * _Nonnull))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)sendReceiptWithOrderId:(NSString * _Nonnull)orderId email:(NSString * _Nullable)email phone:(NSString * _Nullable)phone;
- (void)doKeyedTransactionWithKeyedRequest:(KeyedRequest * _Nonnull)keyedRequest delegate:(id <TransactionDelegate> _Nonnull)delegate;
- (void)doCardReaderTransactionWithReaderInfo:(ReaderInfo * _Nonnull)readerInfo order:(Order * _Nonnull)order delegate:(id <TransactionDelegate> _Nonnull)delegate;
- (void)cancelCardReaderTransactionWithReaderInfo:(ReaderInfo * _Nonnull)readerInfo;
- (void)useReaderWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo delegate:(id <CardReaderDelegate> _Nonnull)delegate;
- (void)scanForBluetoothReaders;
- (BOOL)isConnectedWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo SWIFT_WARN_UNUSED_RESULT;
- (void)releaseReaderWithCardReaderInfo:(ReaderInfo * _Nonnull)cardReaderInfo;
- (void)connectToBTReaderWithReaderInfo:(ReaderInfo * _Nonnull)readerInfo;
- (void)resetReaderWithReaderInfo:(ReaderInfo * _Nonnull)readerInfo;
- (void)doCloseOutTransactionWithSuccess:(void (^ _Nonnull)(BOOL))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)doAddTipTransactionWithPaymentId:(NSString * _Nonnull)paymentId amount:(NSInteger)amount success:(void (^ _Nonnull)(BOOL))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)doVoidTransactionWithPaymentId:(NSString * _Nonnull)paymentId orderId:(NSString * _Nonnull)orderId voidReason:(NSString * _Nullable)voidReason success:(void (^ _Nonnull)(BOOL))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)deleteOrderWithOrderId:(NSString * _Nonnull)orderId success:(void (^ _Nonnull)(BOOL))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
- (void)getMerchantInfoWithSuccess:(void (^ _Nonnull)(Merchant * _Nonnull))success failure:(void (^ _Nonnull)(CloverGoError * _Nonnull))failure;
@end


SWIFT_CLASS("_TtC14clovergoclient13CloverGoError")
@interface CloverGoError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14clovergoclient10CustomItem")
@interface CustomItem : NSObject
@property (nonatomic, strong) TaxRate * _Nullable taxRate;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger price;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic) NSInteger quantity;
@property (nonatomic, readonly) NSInteger total;
@property (nonatomic, readonly) NSInteger tax;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name price:(NSInteger)price quantity:(NSInteger)quantity OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name price:(NSInteger)price quantity:(NSInteger)quantity taxRate:(TaxRate * _Nullable)taxRate createdDate:(NSDate * _Nullable)createdDate;
- (void)delete;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, Env) {
  EnvLive = 0,
  EnvDemo = 1,
  EnvSandbox = 2,
  EnvTest = 3,
  EnvQa = 4,
};

@class ItemCategory;

SWIFT_CLASS("_TtC14clovergoclient9Inventory")
@interface Inventory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable alternateName;
@property (nonatomic, readonly) NSInteger price;
@property (nonatomic, readonly, copy) NSString * _Nullable priceType;
@property (nonatomic) NSInteger stockCount;
@property (nonatomic, copy) NSArray<TaxRate *> * _Nullable taxRates;
@property (nonatomic, copy) NSArray<ItemCategory *> * _Nullable categories;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14clovergoclient13InventoryItem")
@interface InventoryItem : NSObject
@property (nonatomic, strong) Inventory * _Nonnull item;
@property (nonatomic) NSInteger quantity;
@property (nonatomic, readonly) NSInteger total;
@property (nonatomic, readonly) NSInteger tax;
- (nonnull instancetype)initWithInventory:(Inventory * _Nonnull)inventory quantity:(NSInteger)quantity OBJC_DESIGNATED_INITIALIZER;
- (void)updateWithQuantity:(NSInteger)quantity;
- (void)delete;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14clovergoclient12ItemCategory")
@interface ItemCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14clovergoclient12KeyedRequest")
@interface KeyedRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull expDate;
@property (nonatomic, readonly, copy) NSString * _Nonnull cvv;
@property (nonatomic, copy) NSString * _Nullable zipCode;
@property (nonatomic, copy) NSString * _Nullable streetAddress;
@property (nonatomic) BOOL cardPresent;
@property (nonatomic, readonly, strong) Order * _Nonnull order;
- (nonnull instancetype)initWithCardNumber:(NSString * _Nonnull)cardNumber expDate:(NSString * _Nonnull)expDate cvv:(NSString * _Nonnull)cvv order:(Order * _Nonnull)order OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCardNumber:(NSString * _Nonnull)cardNumber expDate:(NSString * _Nonnull)expDate cvv:(NSString * _Nonnull)cvv order:(Order * _Nonnull)order zipCode:(NSString * _Nullable)zipCode streetAddress:(NSString * _Nullable)streetAddress cardPresent:(BOOL)cardPresent;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class OfflineSettings;

SWIFT_CLASS("_TtC14clovergoclient8Merchant")
@interface Merchant : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable mccCode;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable features;
@property (nonatomic, strong) OfflineSettings * _Nullable offlineSettings;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MerchantPropertyType) {
  MerchantPropertyTypeSupportsAuths = 0,
  MerchantPropertyTypeSupportsPreAuths = 1,
  MerchantPropertyTypeSupportsSales = 2,
  MerchantPropertyTypeSupportsVaultCards = 3,
  MerchantPropertyTypeSupportsManualRefunds = 4,
  MerchantPropertyTypeSupportsVoids = 5,
  MerchantPropertyTypeSupportsTipAdjust = 6,
};

typedef SWIFT_ENUM(NSInteger, OfflineMode) {
  OfflineModeAlways = 0,
  OfflineModeNever = 1,
  OfflineModeOn_demand = 2,
};


SWIFT_CLASS("_TtC14clovergoclient15OfflineSettings")
@interface OfflineSettings : NSObject
@property (nonatomic) BOOL enabled;
@property (nonatomic) NSInteger maxDaysAllowedOffline;
@property (nonatomic) NSInteger totalPaymentsLimit;
@property (nonatomic) NSInteger perPaymentLimit;
@property (nonatomic) NSInteger promptThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14clovergoclient5Order")
@interface Order : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSArray<CustomItem *> * _Nonnull customItems;
@property (nonatomic, copy) NSArray<InventoryItem *> * _Nonnull inventoryItems;
@property (nonatomic) NSInteger tip;
@property (nonatomic, copy) NSString * _Nullable externalPaymentId;
@property (nonatomic) NSInteger customTax;
@property (nonatomic) enum CLVGoTransactionType transactionType;
@property (nonatomic, readonly) NSInteger total;
@property (nonatomic, readonly) NSInteger subTotal;
@property (nonatomic) NSInteger tax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)addCustomItemWithItem:(CustomItem * _Nonnull)item;
- (void)addInventoryItemWithItem:(InventoryItem * _Nonnull)item;
@end


SWIFT_PROTOCOL("_TtP14clovergoclient14ProceedOnError_")
@protocol ProceedOnError
- (void)proceedWithValue:(BOOL)value;
@end

enum CardReaderType : NSInteger;

SWIFT_CLASS("_TtC14clovergoclient10ReaderInfo")
@interface ReaderInfo : NSObject
@property (nonatomic) NSInteger batteryPercentage;
@property (nonatomic, copy) NSString * _Nullable serialNumber;
@property (nonatomic) BOOL connected;
@property (nonatomic, readonly) enum CardReaderType readerType;
@property (nonatomic, copy) NSString * _Nullable bluetoothId;
@property (nonatomic, copy) NSString * _Nullable bluetoothName;
@property (nonatomic, copy) NSString * _Nullable readerName;
- (nonnull instancetype)initWithReaderType:(enum CardReaderType)readerType serialNumber:(NSString * _Nullable)serialNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CardReaderType) {
  CardReaderTypeRP350 = 0,
  CardReaderTypeRP450 = 1,
};

@class NSDate;

SWIFT_CLASS("_TtC14clovergoclient6Refund")
@interface Refund : NSObject
@property (nonatomic, readonly, copy) NSString * _Null_unspecified id;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified orderId;
@property (nonatomic, readonly) NSInteger amount;
@property (nonatomic, readonly) NSInteger tax;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified createdTime;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified clientCreatedTime;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified paymentId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14clovergoclient7TaxRate")
@interface TaxRate : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) double rate;
@property (nonatomic, readonly) BOOL isDefault;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name rate:(double)rate isDefault:(BOOL)isDefault OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class TransactionResult;
enum TransactionEvent : NSInteger;

SWIFT_PROTOCOL("_TtP14clovergoclient19TransactionDelegate_")
@protocol TransactionDelegate
- (void)onTransactionResponseWithTransactionResponse:(TransactionResult * _Nonnull)transactionResponse;
- (void)onErrorWithError:(CloverGoError * _Nonnull)error;
- (void)proceedOnErrorWithEvent:(enum TransactionEvent)event proceedOnErrorDelegate:(id <ProceedOnError> _Nonnull)proceedOnErrorDelegate;
- (void)onAidMatchWithCardApplicationIdentifiers:(NSArray<CardApplicationIdentifier *> * _Nonnull)cardApplicationIdentifiers delegate:(id <AidSelection> _Nonnull)delegate;
- (void)onProgressWithEvent:(enum CardReaderEvent)event;
@optional
- (void)addOrderNoteWithDelegate:(id <AddOrderNoteDelegate> _Nonnull)delegate;
@end

typedef SWIFT_ENUM(NSInteger, TransactionEvent) {
  TransactionEventAvs_failure = 0,
  TransactionEventDuplicate_transaction = 1,
  TransactionEventOffline = 2,
  TransactionEventOffline_payment_limit_exceeded = 3,
};


SWIFT_CLASS("_TtC14clovergoclient17TransactionResult")
@interface TransactionResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified orderId;
@property (nonatomic, copy) NSString * _Null_unspecified transactionId;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger amountCharged;
@property (nonatomic) NSInteger taxAmount;
@property (nonatomic) NSInteger tipAmount;
@property (nonatomic, strong) NSDate * _Nullable transactionDate;
@property (nonatomic, copy) NSString * _Nullable cvmResult;
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable mode;
@property (nonatomic, copy) NSString * _Nullable maskedCardNo;
@property (nonatomic, copy) NSString * _Nullable transactionType;
@property (nonatomic, copy) NSString * _Nullable authCode;
@property (nonatomic, copy) NSString * _Nullable cardHolderName;
@property (nonatomic, copy) NSString * _Nullable externalPaymentId;
@property (nonatomic, copy) NSString * _Nullable applicationIdentifier;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
